# Generated by Django 5.2.4 on 2026-01-21 16:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_texto', models.CharField(help_text='Respaldo del nombre por si se borra el usuario', max_length=150)),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('ACCESO', 'Login/Acceso'), ('SALIDA', 'Logout')], max_length=20)),
                ('modelo_afectado', models.CharField(help_text='Ej: Medicamento, Colectivo', max_length=100)),
                ('id_objeto', models.CharField(blank=True, help_text='ID del registro afectado', max_length=50, null=True)),
                ('detalles', models.JSONField(blank=True, default=dict, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Bitácora del Sistema',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='auditoria_b_fecha_h_b77d28_idx'), models.Index(fields=['usuario'], name='auditoria_b_usuario_3713fd_idx'), models.Index(fields=['accion'], name='auditoria_b_accion_bffca7_idx')],
            },
        ),
    ]
