"""
farmacia/views/backup_views.py
Vistas para la gestión y creación de copias de seguridad (Backups) del sistema.
"""
import glob
import gzip
import os
import tarfile
from datetime import datetime

from django.conf import settings
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.views.decorators.cache import never_cache
from django.views.decorators.http import require_http_methods


@never_cache
@login_required
@user_passes_test(lambda u: u.is_superuser or u.rol == 'ADMIN')
def panel_backups(request):
    """Vista principal del panel de backups"""
    backups_dir = os.path.join(settings.BASE_DIR, 'backups')
    if not os.path.exists(backups_dir):
        os.makedirs(backups_dir)
    
    db_backups = []
    media_backups = []
    
    for filepath in glob.glob(os.path.join(backups_dir, '*.sql*')):
        if not filepath.endswith('.tar.gz') and not filepath.endswith('.tar'):
            filename = os.path.basename(filepath)
            size = os.path.getsize(filepath)
            mtime = os.path.getmtime(filepath)
            db_backups.append({
                'filename': filename, 'filepath': filepath, 'size': size,
                'size_mb': round(size / (1024 * 1024), 2),
                'date': datetime.fromtimestamp(mtime), 'tipo': 'database'
            })
    
    for filepath in glob.glob(os.path.join(backups_dir, '*.tar*')):
        filename = os.path.basename(filepath)
        size = os.path.getsize(filepath)
        mtime = os.path.getmtime(filepath)
        media_backups.append({
            'filename': filename, 'filepath': filepath, 'size': size,
            'size_mb': round(size / (1024 * 1024), 2),
            'date': datetime.fromtimestamp(mtime), 'tipo': 'media'
        })
    
    db_backups.sort(key=lambda x: x['date'], reverse=True)
    media_backups.sort(key=lambda x: x['date'], reverse=True)
    
    total_backups = len(db_backups) + len(media_backups)
    total_size = sum([b['size'] for b in db_backups + media_backups])
    total_size_mb = round(total_size / (1024 * 1024), 2)
    
    import shutil
    disk_usage = shutil.disk_usage(settings.BASE_DIR)
    espacio_disponible_gb = round(disk_usage.free / (1024 ** 3), 2)
    
    context = {
        'db_backups': db_backups, 'media_backups': media_backups,
        'total_backups': total_backups, 'total_size_mb': total_size_mb,
        'espacio_disponible_gb': espacio_disponible_gb,
        'ultimo_backup': db_backups[0] if db_backups else None,
    }
    return render(request, 'backups.html', context)


@never_cache
@login_required
@require_http_methods(['POST'])
@user_passes_test(lambda u: u.is_superuser or u.rol == 'ADMIN')
def crear_backup(request):
    """Crea un nuevo backup de base de datos usando Python puro"""
    try:
        import pymysql
        backups_dir = os.path.join(settings.BASE_DIR, 'backups')
        if not os.path.exists(backups_dir):
            os.makedirs(backups_dir)
        
        timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        backup_filename = f'backup_{timestamp}.sql.gz'
        backup_path = os.path.join(backups_dir, backup_filename)
        db_config = settings.DATABASES['default']
        
        connection = pymysql.connect(
            host=db_config['HOST'], port=int(db_config['PORT']),
            user=db_config['USER'], password=db_config['PASSWORD'],
            database=db_config['NAME'], charset='utf8mb4'
        )
        cursor = connection.cursor()
        
        with gzip.open(backup_path, 'wt', encoding='utf-8') as f:
            f.write(f"-- MySQL Backup\n-- Host: {db_config['HOST']}\n-- Database: {db_config['NAME']}\n")
            f.write(f"-- Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n-- Generated by: INVENTFARM Backup System\n\n")
            f.write("SET FOREIGN_KEY_CHECKS=0;\n\n")
            
            cursor.execute("SHOW TABLES")
            tables = cursor.fetchall()
            
            for table_name, in tables:
                f.write(f"\n-- Table structure for `{table_name}`\n")
                f.write(f"DROP TABLE IF EXISTS `{table_name}`;\n")
                cursor.execute(f"SHOW CREATE TABLE `{table_name}`")
                f.write(f"{cursor.fetchone()[1]};\n\n")
                
                cursor.execute(f"SELECT * FROM `{table_name}`")
                rows = cursor.fetchall()
                if rows:
                    f.write(f"-- Data for table `{table_name}` ({len(rows)} rows)\n")
                    cursor.execute(f"SHOW COLUMNS FROM `{table_name}`")
                    columns = [col[0] for col in cursor.fetchall()]
                    columns_str = '`, `'.join(columns)
                    
                    batch_size = 100
                    for i in range(0, len(rows), batch_size):
                        batch = rows[i:i + batch_size]
                        f.write(f"INSERT INTO `{table_name}` (`{columns_str}`) VALUES\n")
                        values_list = []
                        for row in batch:
                            escaped_values = []
                            for value in row:
                                if value is None:
                                    escaped_values.append('NULL')
                                elif isinstance(value, (int, float)):
                                    escaped_values.append(str(value))
                                elif isinstance(value, bytes):
                                    escaped_values.append(f"X'{value.hex()}'")
                                else:
                                    escaped_value = str(value).replace('\\', '\\\\').replace("'", "\\'")
                                    escaped_values.append(f"'{escaped_value}'")
                            values_list.append(f"({', '.join(escaped_values)})")
                        f.write(',\n'.join(values_list))
                        f.write(';\n\n')
            
            f.write("\nSET FOREIGN_KEY_CHECKS=1;\n\n-- Backup completed successfully\n")
        
        cursor.close()
        connection.close()
        
        if not os.path.exists(backup_path):
            raise Exception('El archivo de backup no se creó')
        file_size = os.path.getsize(backup_path)
        
        media_filename = None
        try:
            media_filename = f'media_{timestamp}.tar.gz'
            media_backup_path = os.path.join(backups_dir, media_filename)
            with tarfile.open(media_backup_path, 'w:gz') as tar:
                media_dir = settings.MEDIA_ROOT
                if os.path.exists(media_dir) and os.listdir(media_dir):
                    tar.add(media_dir, arcname='media')
        except Exception as e:
            print(f"⚠️ Error al crear backup de media: {e}")
        
        limpiar_backups_antiguos(backups_dir)
        
        return JsonResponse({
            'success': True, 'message': 'Backup creado exitosamente',
            'details': {
                'database': backup_filename, 'size_mb': round(file_size / (1024*1024), 2),
                'media': media_filename
            }
        })
    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'success': False, 'error': f'Error al crear backup: {str(e)}'}, status=500)


def limpiar_backups_antiguos(backups_dir, max_backups=10):
    try:
        db_backups = glob.glob(os.path.join(backups_dir, 'backup_*.sql*'))
        db_backups.sort(key=os.path.getmtime, reverse=True)
        for backup in db_backups[max_backups:]:
            os.remove(backup)
        
        media_backups = glob.glob(os.path.join(backups_dir, 'media_*.tar*'))
        media_backups.sort(key=os.path.getmtime, reverse=True)
        for backup in media_backups[max_backups:]:
            os.remove(backup)
    except Exception as e:
        print(f"⚠️ Error al limpiar backups antiguos: {e}")


@never_cache
@login_required
@user_passes_test(lambda u: u.is_superuser or u.rol == 'ADMIN')
def descargar_backup(request, filename):
    backups_dir = os.path.join(settings.BASE_DIR, 'backups')
    filepath = os.path.join(backups_dir, filename)
    if not os.path.exists(filepath) or not filepath.startswith(backups_dir):
        return HttpResponse('Archivo no encontrado', status=404)
    with open(filepath, 'rb') as f:
        response = HttpResponse(f.read(), content_type='application/octet-stream')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response


@never_cache
@login_required
@require_http_methods(['POST'])
@user_passes_test(lambda u: u.is_superuser or u.rol == 'ADMIN')
def eliminar_backup(request, filename):
    try:
        backups_dir = os.path.join(settings.BASE_DIR, 'backups')
        filepath = os.path.join(backups_dir, filename)
        if not os.path.exists(filepath) or not filepath.startswith(backups_dir):
            return JsonResponse({'success': False, 'error': 'Archivo no encontrado'}, status=404)
        os.remove(filepath)
        return JsonResponse({'success': True, 'message': f'Backup "{filename}" eliminado correctamente'})
    except Exception as e:
        return JsonResponse({'success': False, 'error': str(e)}, status=500)


@never_cache
@login_required
@require_http_methods(['POST'])
@user_passes_test(lambda u: u.is_superuser or u.rol == 'ADMIN')
def restaurar_backup(request):
    try:
        import pymysql
        filename = request.POST.get('filename')
        if not filename:
            return JsonResponse({'success': False, 'error': 'No se especificó archivo'}, status=400)
        
        backups_dir = os.path.join(settings.BASE_DIR, 'backups')
        filepath = os.path.join(backups_dir, filename)
        if not os.path.exists(filepath):
            return JsonResponse({'success': False, 'error': 'Archivo no encontrado'}, status=404)
        
        session_key = request.session.session_key
        session_data = None
        if session_key:
            from django.contrib.sessions.models import Session
            try:
                current_session = Session.objects.get(session_key=session_key)
                session_data = {
                    'session_key': current_session.session_key,
                    'session_data': current_session.session_data,
                    'expire_date': current_session.expire_date
                }
            except Session.DoesNotExist: pass
        
        db_config = settings.DATABASES['default']
        connection = pymysql.connect(
            host=db_config['HOST'], port=int(db_config['PORT']),
            user=db_config['USER'], password=db_config['PASSWORD'],
            database=db_config['NAME'], charset='utf8mb4', autocommit=False
        )
        cursor = connection.cursor()
        
        try:
            cursor.execute("SET FOREIGN_KEY_CHECKS=0")
            if filename.endswith('.gz'):
                with gzip.open(filepath, 'rt', encoding='utf-8') as f:
                    sql_content = f.read()
            else:
                with open(filepath, 'r', encoding='utf-8') as f:
                    sql_content = f.read()
            
            statements = []
            current_statement = []
            for line in sql_content.split('\n'):
                line = line.strip()
                if not line or line.startswith('--'): continue
                current_statement.append(line)
                if line.endswith(';'):
                    statement = ' '.join(current_statement)
                    if statement and not statement.startswith('--'):
                        statements.append(statement)
                    current_statement = []
            
            executed = 0
            for statement in statements:
                statement = statement.strip()
                if statement:
                    try:
                        cursor.execute(statement)
                        executed += 1
                    except Exception: pass
            
            connection.commit()
            
            if session_data:
                try:
                    cursor.execute("DELETE FROM django_session WHERE session_key = %s", (session_data['session_key'],))
                    cursor.execute(
                        "INSERT INTO django_session (session_key, session_data, expire_date) VALUES (%s, %s, %s)",
                        (session_data['session_key'], session_data['session_data'], session_data['expire_date'])
                    )
                    connection.commit()
                except Exception: pass
            
            cursor.execute("SET FOREIGN_KEY_CHECKS=1")
            request.session.modified = False
            return JsonResponse({'success': True, 'message': 'Backup restaurado exitosamente'})
        except Exception as e:
            connection.rollback()
            return JsonResponse({'success': False, 'error': f'Error en la restauración: {str(e)}'}, status=500)
        finally:
            cursor.close()
            connection.close()
    except Exception as e:
        return JsonResponse({'success': False, 'error': f'Error en el proceso: {str(e)}'}, status=500)


@never_cache
@login_required
@require_http_methods(['POST'])
@user_passes_test(lambda u: u.is_superuser or u.rol == 'ADMIN')
def subir_backup(request):
    """Sube un archivo de backup previamente descargado o externo"""
    try:
        if 'archivo_backup' not in request.FILES:
            return JsonResponse({'success': False, 'error': 'No se proporcionó ningún archivo'}, status=400)
            
        archivo = request.FILES['archivo_backup']
        nombre_original = archivo.name
        
        backups_dir = os.path.join(settings.BASE_DIR, 'backups')
        if not os.path.exists(backups_dir):
            os.makedirs(backups_dir)
            
        timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        if '.sql.gz' in nombre_original:
            extension = '.sql.gz'
        elif '.sql' in nombre_original:
            extension = '.sql'
        elif '.tar.gz' in nombre_original:
            extension = '.tar.gz'
        else:
            return JsonResponse({'success': False, 'error': 'Formato de archivo no soportado. Debe ser .sql, .sql.gz o .tar.gz'}, status=400)
            
        nuevo_nombre = f'backup_manual_{timestamp}{extension}'
        if extension == '.tar.gz':
            nuevo_nombre = f'media_manual_{timestamp}{extension}'
            
        ruta_guardado = os.path.join(backups_dir, nuevo_nombre)
        with open(ruta_guardado, 'wb+') as destino:
            for chunk in archivo.chunks():
                destino.write(chunk)
                
        limpiar_backups_antiguos(backups_dir)
        return JsonResponse({'success': True, 'message': f'Archivo subido correctamente como {nuevo_nombre}', 'filename': nuevo_nombre})
    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'success': False, 'error': str(e)}, status=500)
