# Generated by Django 5.2.4 on 2025-11-28 16:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacia', '0016_lote_unique_medicamento_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=50, unique=True)),
                ('numero_cama', models.CharField(max_length=20)),
                ('servicio', models.CharField(help_text='Ej: Urgencias, Piso 2, UCI', max_length=100)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta_farmacia', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('RESPONDIDO', 'Respondido'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('observaciones_enfermeria', models.TextField(blank=True, help_text='Indicaciones especiales')),
                ('respuesta_farmacia', models.TextField(blank=True, help_text='Comentarios sobre disponibilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enfermero_solicitante', models.ForeignKey(limit_choices_to={'rol': 'ENFERMERIA'}, on_delete=django.db.models.deletion.PROTECT, related_name='colectivos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('farmaceutico_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'FARMACIA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colectivos_atendidos', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colectivos', to='farmacia.paciente')),
            ],
            options={
                'verbose_name': 'Colectivo',
                'verbose_name_plural': 'Colectivos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ColectivoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_surtida', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('disponible', models.BooleanField(default=True, help_text='¿Farmacia tiene este medicamento?')),
                ('comentario_farmacia', models.TextField(blank=True, help_text='Ej: Stock insuficiente, cambiar por...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='enfermeria.colectivo')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento')),
            ],
            options={
                'verbose_name': 'Medicamento del Colectivo',
                'verbose_name_plural': 'Medicamentos del Colectivo',
                'ordering': ['medicamento__descripcion'],
                'unique_together': {('colectivo', 'medicamento')},
            },
        ),
    ]
