# Generated by Django 5.2.4 on 2025-12-12 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=50, unique=True)),
                ('tipo_colectivo', models.CharField(choices=[('PACIENTE', 'Colectivo para Paciente'), ('STOCK', 'Colectivo para Stock')], default='PACIENTE', max_length=20, verbose_name='Tipo de Colectivo')),
                ('numero_cama', models.CharField(blank=True, max_length=20, null=True)),
                ('servicio', models.CharField(help_text='Ej: Urgencias, Piso 2, UCI, Quirófano', max_length=100)),
                ('turno', models.CharField(blank=True, choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOCTURNO', 'Nocturno')], max_length=20, null=True, verbose_name='Turno Solicitante')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta_farmacia', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('RESPONDIDO', 'Respondido'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('observaciones_enfermeria', models.TextField(blank=True, help_text='Indicaciones especiales')),
                ('respuesta_farmacia', models.TextField(blank=True, help_text='Comentarios sobre disponibilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colectivo',
                'verbose_name_plural': 'Colectivos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ColectivoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_surtida', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('disponible', models.BooleanField(default=True, help_text='¿Farmacia tiene este medicamento?')),
                ('comentario_farmacia', models.TextField(blank=True, help_text='Ej: Stock insuficiente, cambiar por...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento del Colectivo',
                'verbose_name_plural': 'Medicamentos del Colectivo',
                'ordering': ['medicamento__descripcion'],
            },
        ),
    ]
