# Generated by Django 5.2.4 on 2025-12-05 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0001_initial'),
        ('farmacia', '0017_receta_observaciones_faltantes_medicamentonosurtido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colectivo',
            name='tipo_colectivo',
            field=models.CharField(choices=[('PACIENTE', 'Colectivo para Paciente'), ('STOCK', 'Colectivo para Stock')], default='PACIENTE', max_length=20, verbose_name='Tipo de Colectivo'),
        ),
        migrations.AddField(
            model_name='colectivo',
            name='turno',
            field=models.CharField(blank=True, choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOCTURNO', 'Nocturno')], max_length=20, null=True, verbose_name='Turno Solicitante'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='numero_cama',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colectivos', to='farmacia.paciente'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='servicio',
            field=models.CharField(help_text='Ej: Urgencias, Piso 2, UCI, Quirófano', max_length=100),
        ),
        migrations.AddIndex(
            model_name='colectivo',
            index=models.Index(fields=['tipo_colectivo', 'estado'], name='enfermeria__tipo_co_f3be96_idx'),
        ),
        migrations.AddIndex(
            model_name='colectivo',
            index=models.Index(fields=['fecha_solicitud'], name='enfermeria__fecha_s_ea83ef_idx'),
        ),
    ]
