# Generated by Django 5.2.4 on 2025-12-12 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enfermeria', '0001_initial'),
        ('farmacia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colectivo',
            name='enfermero_solicitante',
            field=models.ForeignKey(limit_choices_to={'rol': 'ENFERMERIA'}, on_delete=django.db.models.deletion.PROTECT, related_name='colectivos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colectivo',
            name='farmaceutico_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'FARMACIA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colectivos_atendidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colectivo',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colectivos', to='farmacia.paciente'),
        ),
        migrations.AddField(
            model_name='colectivomedicamento',
            name='colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='enfermeria.colectivo'),
        ),
        migrations.AddField(
            model_name='colectivomedicamento',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento'),
        ),
        migrations.AddIndex(
            model_name='colectivo',
            index=models.Index(fields=['tipo_colectivo', 'estado'], name='enfermeria__tipo_co_f3be96_idx'),
        ),
        migrations.AddIndex(
            model_name='colectivo',
            index=models.Index(fields=['fecha_solicitud'], name='enfermeria__fecha_s_ea83ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='colectivomedicamento',
            unique_together={('colectivo', 'medicamento')},
        ),
    ]
