# Generated by Django 5.2.4 on 2026-01-09 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colectivomedicamento',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Comentarios generales sobre este medicamento', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='colectivomedicamento',
            name='cantidad_solicitada',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Solicitada'),
        ),
        migrations.AlterField(
            model_name='colectivomedicamento',
            name='cantidad_surtida',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Surtida'),
        ),
        migrations.AlterField(
            model_name='colectivomedicamento',
            name='comentario_farmacia',
            field=models.TextField(blank=True, help_text='Ej: Stock insuficiente, cambiar por...', verbose_name='Comentario de Farmacia'),
        ),
        migrations.AlterField(
            model_name='colectivomedicamento',
            name='disponible',
            field=models.BooleanField(default=True, help_text='¿Farmacia tiene este medicamento?', verbose_name='Disponible en Farmacia'),
        ),
    ]
