# Generated by Django 5.2.4 on 2026-01-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0003_colectivomedicamento_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colectivo',
            options={'ordering': ['-fecha_solicitud'], 'permissions': [('create_colectivo', 'Puede crear colectivos'), ('respond_colectivo', 'Puede responder colectivos'), ('complete_colectivo', 'Puede completar colectivos')], 'verbose_name': 'Colectivo', 'verbose_name_plural': 'Colectivos'},
        ),
    ]
