# Generated by Django 5.2.4 on 2025-12-12 22:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Almacén')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuenteFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuente de Financiamiento',
                'verbose_name_plural': 'Fuentes de Financiamiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CENTRO_SALUD', 'Centro de Salud'), ('FARMACIA', 'Farmacia'), ('LABORATORIO', 'Laboratorio'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('codigo_barras', models.CharField(blank=True, max_length=40, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Unitario')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('unidades_por_caja', models.IntegerField(default=1, help_text='Solo aplica si es caja')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proveedor')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('FARMACIA', 'Farmacia'), ('ENFERMERIA', 'Enfermería'), ('ROPERIA', 'Ropería')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.departamento')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, help_text='Dejar vacío para generación automática', max_length=50, null=True, verbose_name='Folio')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Entrada')),
                ('tipo_entrada', models.CharField(choices=[('ALMACEN', 'Entrada por Almacén'), ('TRANSFERENCIA', 'Entrada por Transferencia')], max_length=20, verbose_name='Tipo de Entrada')),
                ('contrato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Contrato')),
                ('proceso', models.CharField(max_length=100, verbose_name='Proceso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.almacen', verbose_name='Almacén')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('fuente_financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.fuentefinanciamiento', verbose_name='Fuente de Financiamiento')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.institucion', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Entrada de Medicamentos',
                'verbose_name_plural': 'Entradas de Medicamentos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CPMMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='Consumo Promedio Mensual (CPM)')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medicamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpm_medicamento', to='farmacia.medicamento')),
            ],
            options={
                'verbose_name': 'CPM por Medicamento',
                'verbose_name_plural': 'CPMs por Medicamento',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.presentacion', verbose_name='Presentación'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('lote_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_caducidad', models.DateField()),
                ('existencia', models.IntegerField(default=0)),
                ('alerta_stock_enviada', models.BooleanField(default=False)),
                ('cpm', models.PositiveIntegerField(default=0, verbose_name='Consumo Promedio Mensual')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento')),
                ('presentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia.presentacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50, verbose_name='Número de Lote')),
                ('caducidad', models.DateField(verbose_name='Fecha de Caducidad')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='farmacia.entrada', verbose_name='Entrada')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento', verbose_name='Medicamento')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.presentacion', verbose_name='Presentación')),
            ],
            options={
                'verbose_name': 'Detalle de Entrada',
                'verbose_name_plural': 'Detalles de Entrada',
            },
        ),
        migrations.CreateModel(
            name='CPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.presentacion')),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_folio', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_surtido', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('completa', 'Completa'), ('parcial', 'Parcial'), ('no_surtida', 'No Surtida')], max_length=20)),
                ('origen', models.CharField(choices=[('urgencias', 'Urgencias'), ('labor', 'Labor'), ('expulsion', 'Expulsión'), ('tococirugia', 'Tococirugía'), ('hospitalizacion_pediatria', 'Hospitalización Pediatría'), ('hospitalizacion_adultos', 'Hospitalización Adultos'), ('consulta_externa', 'Consulta Externa'), ('quirofano', 'Quirófano'), ('sala_de_choque', 'Sala de Choque'), ('cuidados_intensivos', 'Cuidados Intensivos'), ('uci_neonatal', 'UCI Neonatal'), ('uci_adultos', 'UCI Adultos'), ('ucip', 'UCI Pediátrica')], max_length=50)),
                ('observaciones_faltantes', models.TextField(blank=True, help_text='Registro de medicamentos que no pudieron ser surtidos y el motivo', null=True, verbose_name='Medicamentos No Surtidos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.paciente')),
                ('surtido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_surtidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoNoSurtido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_descripcion', models.CharField(max_length=200, verbose_name='Descripción del Medicamento')),
                ('cantidad_solicitada', models.IntegerField(verbose_name='Cantidad Solicitada')),
                ('motivo', models.TextField(verbose_name='Motivo de No Surtido')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_no_surtidos', to='farmacia.receta')),
            ],
            options={
                'verbose_name': 'Medicamento No Surtido',
                'verbose_name_plural': 'Medicamentos No Surtidos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_surtida', models.IntegerField()),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.lote')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.lote')),
            ],
        ),
        migrations.AddConstraint(
            model_name='entrada',
            constraint=models.UniqueConstraint(condition=models.Q(('folio__isnull', False)), fields=('folio', 'institucion'), name='folio_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('medicamento', 'lote_codigo'), name='unique_medicamento_lote'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleentrada',
            unique_together={('entrada', 'medicamento', 'lote')},
        ),
        migrations.AlterUniqueTogether(
            name='cpm',
            unique_together={('medicamento', 'presentacion')},
        ),
    ]
