# Generated by Django 5.2.4 on 2025-07-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_presentacion_lote_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='unidades_por_caja',
            field=models.IntegerField(default=1, help_text='Solo aplica si es caja'),
        ),
        migrations.CreateModel(
            name='CPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.presentacion')),
            ],
            options={
                'unique_together': {('medicamento', 'presentacion')},
            },
        ),
    ]
