# Generated by Django 5.2.4 on 2025-12-15 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_alter_entrada_almacen_alter_entrada_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario (lote)'),
        ),
    ]
