# Generated by Django 5.2.4 on 2025-07-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_presentacion_unidades_por_caja_cpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='alerta_stock_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
