# Generated by Django 5.2.4 on 2025-12-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_receta_precio_total_receta_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='precio_total',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='recetamedicamento',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recetamedicamento',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
