# Generated by Django 5.2.4 on 2025-07-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_lote_alerta_stock_enviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cpm',
            field=models.PositiveIntegerField(default=0, verbose_name='Consumo Promedio Mensual'),
        ),
    ]
