# Generated by Django 5.2.4 on 2025-12-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_remove_receta_precio_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
