# Generated by Django 5.2.4 on 2025-08-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_proveedor_medicamento_costo_medicamento_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
