# Generated by Django 5.2.4 on 2026-01-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_alter_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'permissions': [('view_medicamento_readonly', 'Puede ver medicamentos (solo lectura)')], 'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='receta',
            options={'permissions': [('process_receta', 'Puede procesar recetas'), ('view_receta_readonly', 'Puede ver recetas (solo lectura)')], 'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.AlterModelOptions(
            name='usuariopersonalizado',
            options={'permissions': [('view_inventory_readonly', 'Puede ver inventario (solo lectura)'), ('manage_pharmacy', 'Puede administrar farmacia completa'), ('manage_nursing', 'Puede administrar enfermería completa')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('FARMACIA', 'Farmacéutico'), ('ENFERMERIA', 'Enfermero/a'), ('MEDICO', 'Médico/a')], max_length=20),
        ),
    ]
