# Generated by Django 5.2.4 on 2025-08-06 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0008_alter_medicamento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Almacén')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FuenteFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuente de Financiamiento',
                'verbose_name_plural': 'Fuentes de Financiamiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CENTRO_SALUD', 'Centro de Salud'), ('FARMACIA', 'Farmacia'), ('LABORATORIO', 'Laboratorio'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['-fecha'], 'verbose_name': 'Entrada de Medicamentos', 'verbose_name_plural': 'Entradas de Medicamentos'},
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='fecha_hora',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='lote',
        ),
        migrations.AddField(
            model_name='entrada',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='contrato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Contrato'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='folio',
            field=models.CharField(default='B01', max_length=50, unique=True, verbose_name='Folio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='proceso',
            field=models.CharField(default='NO SE', max_length=100, verbose_name='Proceso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='recibido_por',
            field=models.ForeignKey(default='ELIU', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipo_entrada',
            field=models.CharField(choices=[('ALMACEN', 'Entrada por Almacén'), ('TRANSFERENCIA', 'Entrada por Transferencia')], default='Por almacen', max_length=20, verbose_name='Tipo de Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='farmacia.almacen', verbose_name='Almacén'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='fuente_financiamiento',
            field=models.ForeignKey(default='INSABI', on_delete=django.db.models.deletion.PROTECT, to='farmacia.fuentefinanciamiento', verbose_name='Fuente de Financiamiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='institucion',
            field=models.ForeignKey(default='SESVER', on_delete=django.db.models.deletion.PROTECT, to='farmacia.institucion', verbose_name='Institución'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50, verbose_name='Número de Lote')),
                ('caducidad', models.DateField(verbose_name='Fecha de Caducidad')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='farmacia.entrada', verbose_name='Entrada')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento', verbose_name='Medicamento')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.presentacion', verbose_name='Presentación')),
            ],
            options={
                'verbose_name': 'Detalle de Entrada',
                'verbose_name_plural': 'Detalles de Entrada',
                'unique_together': {('entrada', 'medicamento', 'lote')},
            },
        ),
    ]
