# Generated by Django 5.2.4 on 2026-01-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0008_alter_medicamento_options_alter_receta_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosPersonalizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permiso Personalizado',
                'verbose_name_plural': 'Permisos Personalizados',
                'permissions': [('view_reportes', 'Puede ver reportes y estadísticas'), ('export_reportes', 'Puede exportar reportes a Excel/PDF'), ('view_carga_masiva', 'Puede acceder a carga masiva de Excel'), ('upload_carga_masiva', 'Puede subir archivos de carga masiva'), ('view_salidas', 'Puede ver historial de salidas'), ('create_salida', 'Puede registrar salidas de medicamentos'), ('view_inventario_completo', 'Puede ver todo el inventario'), ('edit_inventario', 'Puede editar el inventario'), ('manage_catalogos', 'Puede gestionar catálogos (presentaciones, proveedores)'), ('manage_cpm', 'Puede gestionar CPM de medicamentos')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
