# Generated by Django 5.2.4 on 2025-08-11 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0009_almacen_fuentefinanciamiento_institucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.presentacion', verbose_name='Presentación'),
        ),
    ]
