# Generated by Django 5.2.4 on 2026-08-17 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0009_permisospersonalizados'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('institucion_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to='farmacia.institucion', verbose_name='Institución Destino')),
            ],
            options={
                'verbose_name': 'Salida por Transferencia',
                'verbose_name_plural': 'Salidas por Transferencia',
                'ordering': ['-fecha'],
                'permissions': [('create_transferencia', 'Puede registrar salidas por transferencia'), ('view_transferencia', 'Puede ver historial de transferencias')],
            },
        ),
        migrations.CreateModel(
            name='DetalleSalidaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.lote')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='farmacia.salidatransferencia')),
            ],
        ),
    ]
