# Generated by Django 5.2.4 on 2025-08-11 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_medicamento_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Entrada'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='folio',
            field=models.CharField(blank=True, help_text='Dejar vacío para generación automática', max_length=50, null=True, verbose_name='Folio'),
        ),
        migrations.AddConstraint(
            model_name='entrada',
            constraint=models.UniqueConstraint(condition=models.Q(('folio__isnull', False)), fields=('folio', 'institucion'), name='folio_por_institucion'),
        ),
    ]
