# Generated by Django 5.2.4 on 2026-08-18 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_salidatransferencia_detallesalidatransferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoNoDisponibleTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_descripcion', models.CharField(max_length=200)),
                ('cantidad_solicitada', models.IntegerField()),
                ('motivo', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_no_disponibles', to='farmacia.salidatransferencia')),
            ],
            options={
                'ordering': ['medicamento_descripcion'],
            },
        ),
    ]
