# Generated by Django 5.2.4 on 2026-08-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0011_medicamentonodisponibletransferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='contrato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de contrato'),
        ),
        migrations.AddField(
            model_name='lote',
            name='origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de entrada'),
        ),
    ]
