# Generated by Django 5.2.4 on 2025-09-08 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0011_alter_entrada_fecha_alter_entrada_folio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPMMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='Consumo Promedio Mensual (CPM)')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medicamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpm_medicamento', to='farmacia.medicamento')),
            ],
            options={
                'verbose_name': 'CPM por Medicamento',
                'verbose_name_plural': 'CPMs por Medicamento',
            },
        ),
    ]
