# Generated by Django 5.2.4 on 2026-08-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0012_lote_contrato_lote_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='contrato',
        ),
        migrations.AddField(
            model_name='lote',
            name='fuente_financiamiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente de Financiamiento'),
        ),
    ]
