# Generated by Django 5.2.4 on 2025-11-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0012_cpmmedicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetamedicamento',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.lote'),
        ),
    ]
