# Generated by Django 5.2.4 on 2026-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0013_remove_lote_contrato_lote_fuente_financiamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='contrato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de contrato'),
        ),
    ]
