# Generated by Django 5.2.4 on 2025-11-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0014_receta_surtido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
