# Generated by Django 5.2.4 on 2026-09-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0014_lote_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAntibioticosWHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_atc', models.CharField(db_index=True, max_length=20, unique=True)),
                ('categoria_aware', models.CharField(choices=[('Access', 'Access'), ('Watch', 'Watch'), ('Reserve', 'Reserve')], max_length=10)),
                ('valor_ddd_gramos', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fuente_ddd', models.CharField(blank=True, choices=[('herramienta_calculo', 'Herramienta de cálculo'), ('manual', 'Captura manual')], max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Catálogo WHO AWaRe/ATC',
                'verbose_name_plural': 'Catálogo WHO AWaRe/ATC',
            },
        ),
        migrations.AddField(
            model_name='medicamento',
            name='categoria_aware',
            field=models.CharField(blank=True, choices=[('Access', 'Access'), ('Watch', 'Watch'), ('Reserve', 'Reserve')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='codigo_atc',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='es_antibiotico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='gramos_por_pieza',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='valor_ddd_gramos',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='via_administracion',
            field=models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('INTRAMUSCULAR', 'Intramuscular'), ('INTRAVENOSA', 'Intravenosa')], max_length=20, null=True),
        ),
    ]
