# Generated by Django 5.2.4 on 2025-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0015_alter_paciente_curp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('medicamento', 'lote_codigo'), name='unique_medicamento_lote'),
        ),
    ]
