# Generated by Django 5.2.4 on 2026-09-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0015_catalogoantibioticoswho_medicamento_categoria_aware_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogoantibioticoswho',
            old_name='valor_ddd_gramos',
            new_name='valor_atc',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='valor_ddd_gramos',
            new_name='valor_atc',
        ),
    ]
