# Generated by Django 5.2.4 on 2025-12-02 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0016_lote_unique_medicamento_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='observaciones_faltantes',
            field=models.TextField(blank=True, help_text='Registro de medicamentos que no pudieron ser surtidos y el motivo', null=True, verbose_name='Medicamentos No Surtidos'),
        ),
        migrations.CreateModel(
            name='MedicamentoNoSurtido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_descripcion', models.CharField(max_length=200, verbose_name='Descripción del Medicamento')),
                ('cantidad_solicitada', models.IntegerField(verbose_name='Cantidad Solicitada')),
                ('motivo', models.TextField(verbose_name='Motivo de No Surtido')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_no_surtidos', to='farmacia.receta')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicamento No Surtido',
                'verbose_name_plural': 'Medicamentos No Surtidos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
