# Generated by Django 5.2.4 on 2026-09-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0016_rename_valor_ddd_gramos_catalogoantibioticoswho_valor_atc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fuente_financiamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.fuentefinanciamiento', verbose_name='Fuente de Financiamiento'),
        ),
    ]
