# Generated by Django 5.2.4 on 2026-09-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0017_alter_entrada_fuente_financiamiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogoantibioticoswho',
            old_name='fuente_ddd',
            new_name='fuente_valor_atc',
        ),
    ]
