# Generated by Django 5.2.17 on 2026-10-01 16:17

import uuid
from django.db import migrations, models


def crear_control_respaldo(apps, schema_editor):
    apps.get_model('farmacia', 'ControlRespaldo').objects.get_or_create(clave=1)


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0020_perfiles_operativos_y_seguridad_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRespaldo',
            fields=[
                ('clave', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Control interno de respaldos',
                'verbose_name_plural': 'Control interno de respaldos',
            },
        ),
        migrations.CreateModel(
            name='TrabajoRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('CREAR', 'Crear copia'), ('RESTAURAR', 'Restaurar copia')], max_length=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'En espera'), ('EJECUTANDO', 'En ejecución'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=12)),
                ('solicitado_por', models.CharField(blank=True, max_length=150)),
                ('archivo_base_datos', models.CharField(blank=True, max_length=255)),
                ('progreso', models.PositiveSmallIntegerField(default=0)),
                ('etapa', models.CharField(default='En espera', max_length=160)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Trabajo de respaldo',
                'verbose_name_plural': 'Trabajos de respaldo',
                'ordering': ('-creado_en',),
                'indexes': [models.Index(fields=['estado', 'creado_en'], name='trab_respaldo_estado_fecha_idx'), models.Index(fields=['tipo', 'estado'], name='trab_respaldo_tipo_estado_idx')],
            },
        ),
        migrations.RunPython(crear_control_respaldo, migrations.RunPython.noop),
    ]
